#pragma once
#define JUCE_GLOBAL_MODULE_SETTINGS_INCLUDED 1
#define JUCE_MODULE_AVAILABLE_juce_audio_basics 1
#define JUCE_MODULE_AVAILABLE_juce_audio_devices 1
#define JUCE_MODULE_AVAILABLE_juce_audio_formats 1
#define JUCE_MODULE_AVAILABLE_juce_audio_processors 1
#define JUCE_MODULE_AVAILABLE_juce_audio_processors_headless 1
#define JUCE_MODULE_AVAILABLE_juce_audio_utils 1
#define JUCE_MODULE_AVAILABLE_juce_core 1
#define JUCE_MODULE_AVAILABLE_juce_data_structures 1
#define JUCE_MODULE_AVAILABLE_juce_events 1
#define JUCE_MODULE_AVAILABLE_juce_graphics 1
#define JUCE_MODULE_AVAILABLE_juce_gui_basics 1
#define JUCE_MODULE_AVAILABLE_juce_gui_extra 1
#define JUCE_MODULE_AVAILABLE_juce_midi_ci 1
#define JUCE_WEB_BROWSER 0
#define JUCE_USE_CURL 0
#define JUCE_USE_FLAC 0
#define JUCE_USE_WINDOWS_MEDIA_FORMAT 0
#define JUCE_PLUGINHOST_VST 0
#define JUCE_PLUGINHOST_VST3 0
#define JUCE_PLUGINHOST_AU 0
#define JUCE_PLUGINHOST_LADSPA 0
#define JUCE_PLUGINHOST_LV2 0
#define JUCE_PLUGINHOST_ARA 0
#define JUCE_STRICT_REFCOUNTEDPOINTER 1
#define JUCE_DONT_DECLARE_PROJECTINFO 1
#define JUCE_DISPLAY_SPLASH_SCREEN 0
#define JUCE_REPORT_APP_USAGE 0
#define JucePlugin_Name "RiJV880"
#define JUCE_APP_VERSION "0.1.0"
#define JUCE_APP_VERSION_HEX 0x100
